---
version: "3.5"
services:
  runtime:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.runtime
    volumes:
      - ./app:/var/task

  tools:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.tools
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./app:/var/opt/app:ro,delegated
      - ~/.aws/credentials:/home/.aws/credentials:ro
    ports:
      - 3000
    environment:
      - AWS_ACCESS_KEY_ID=NONE
      - AWS_SECRET_ACCESS_KEY=NONE
